// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/disgover.proto

/*
Package disgover is a generated protocol buffer package.

It is generated from these files:
	proto/disgover.proto

It has these top-level messages:
	Endpoint
	Contact
	ContactList
	FindRequest
	Empty
*/
package disgover

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Endpoint struct {
	Host string `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
	Port int64  `protobuf:"varint,2,opt,name=Port" json:"Port,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Endpoint) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Contact struct {
	Id       []byte    `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Endpoint *Endpoint `protobuf:"bytes,2,opt,name=Endpoint" json:"Endpoint,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Contact) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type ContactList struct {
	Id []*Contact `protobuf:"bytes,1,rep,name=Id" json:"Id,omitempty"`
}

func (m *ContactList) Reset()                    { *m = ContactList{} }
func (m *ContactList) String() string            { return proto.CompactTextString(m) }
func (*ContactList) ProtoMessage()               {}
func (*ContactList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ContactList) GetId() []*Contact {
	if m != nil {
		return m.Id
	}
	return nil
}

type FindRequest struct {
	ContactId []byte   `protobuf:"bytes,1,opt,name=ContactId,proto3" json:"ContactId,omitempty"`
	Sender    *Contact `protobuf:"bytes,2,opt,name=Sender" json:"Sender,omitempty"`
}

func (m *FindRequest) Reset()                    { *m = FindRequest{} }
func (m *FindRequest) String() string            { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()               {}
func (*FindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindRequest) GetContactId() []byte {
	if m != nil {
		return m.ContactId
	}
	return nil
}

func (m *FindRequest) GetSender() *Contact {
	if m != nil {
		return m.Sender
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Endpoint)(nil), "disgover.Endpoint")
	proto.RegisterType((*Contact)(nil), "disgover.Contact")
	proto.RegisterType((*ContactList)(nil), "disgover.ContactList")
	proto.RegisterType((*FindRequest)(nil), "disgover.FindRequest")
	proto.RegisterType((*Empty)(nil), "disgover.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DisgoverRPC service

type DisgoverRPCClient interface {
	PeerPingGrpc(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Contact, error)
	PeerFindGrpc(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Contact, error)
	PeerFindAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactList, error)
}

type disgoverRPCClient struct {
	cc *grpc.ClientConn
}

func NewDisgoverRPCClient(cc *grpc.ClientConn) DisgoverRPCClient {
	return &disgoverRPCClient{cc}
}

func (c *disgoverRPCClient) PeerPingGrpc(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := grpc.Invoke(ctx, "/disgover.DisgoverRPC/PeerPingGrpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disgoverRPCClient) PeerFindGrpc(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := grpc.Invoke(ctx, "/disgover.DisgoverRPC/PeerFindGrpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disgoverRPCClient) PeerFindAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactList, error) {
	out := new(ContactList)
	err := grpc.Invoke(ctx, "/disgover.DisgoverRPC/PeerFindAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DisgoverRPC service

type DisgoverRPCServer interface {
	PeerPingGrpc(context.Context, *Contact) (*Contact, error)
	PeerFindGrpc(context.Context, *FindRequest) (*Contact, error)
	PeerFindAll(context.Context, *Empty) (*ContactList, error)
}

func RegisterDisgoverRPCServer(s *grpc.Server, srv DisgoverRPCServer) {
	s.RegisterService(&_DisgoverRPC_serviceDesc, srv)
}

func _DisgoverRPC_PeerPingGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoverRPCServer).PeerPingGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgover.DisgoverRPC/PeerPingGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoverRPCServer).PeerPingGrpc(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisgoverRPC_PeerFindGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoverRPCServer).PeerFindGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgover.DisgoverRPC/PeerFindGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoverRPCServer).PeerFindGrpc(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisgoverRPC_PeerFindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoverRPCServer).PeerFindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgover.DisgoverRPC/PeerFindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoverRPCServer).PeerFindAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DisgoverRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "disgover.DisgoverRPC",
	HandlerType: (*DisgoverRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PeerPingGrpc",
			Handler:    _DisgoverRPC_PeerPingGrpc_Handler,
		},
		{
			MethodName: "PeerFindGrpc",
			Handler:    _DisgoverRPC_PeerFindGrpc_Handler,
		},
		{
			MethodName: "PeerFindAll",
			Handler:    _DisgoverRPC_PeerFindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/disgover.proto",
}

func init() { proto.RegisterFile("proto/disgover.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xd7, 0xee, 0x7d, 0xf7, 0xe7, 0x64, 0x28, 0x1e, 0x1c, 0x8c, 0xe1, 0xc5, 0xcc, 0x55,
	0xbd, 0xa9, 0x52, 0x41, 0xc1, 0x3b, 0x99, 0x53, 0x0b, 0x5e, 0x94, 0x08, 0xde, 0xeb, 0x12, 0x46,
	0x60, 0x26, 0x35, 0x8d, 0x82, 0x5f, 0xcd, 0x4f, 0x27, 0x89, 0x69, 0x3b, 0xe8, 0xee, 0x72, 0xce,
	0x79, 0x7e, 0xcf, 0x79, 0x7a, 0x0a, 0xc7, 0xa5, 0xd1, 0x56, 0x9f, 0x73, 0x59, 0x6d, 0xf4, 0x97,
	0x30, 0xa9, 0x2f, 0x71, 0x54, 0xd7, 0x34, 0x83, 0xd1, 0x4a, 0xf1, 0x52, 0x4b, 0x65, 0x11, 0xe1,
	0xdf, 0xa3, 0xae, 0xec, 0x2c, 0x5a, 0x44, 0xc9, 0x98, 0xf9, 0xb7, 0xeb, 0x15, 0xda, 0xd8, 0x59,
	0xbc, 0x88, 0x92, 0x3e, 0xf3, 0x6f, 0x9a, 0xc3, 0x70, 0xa9, 0x95, 0x7d, 0x5d, 0x5b, 0x3c, 0x80,
	0x38, 0xe7, 0x1e, 0x98, 0xb0, 0x38, 0xe7, 0x98, 0xb6, 0x76, 0x1e, 0x21, 0x19, 0xa6, 0xcd, 0xee,
	0x7a, 0xc2, 0x1a, 0x0d, 0xbd, 0x00, 0x12, 0xac, 0x9e, 0x64, 0x65, 0xf1, 0x34, 0xd8, 0xf5, 0x13,
	0x92, 0x1d, 0xb5, 0x60, 0x90, 0xb8, 0x0d, 0xf4, 0x05, 0xc8, 0xbd, 0x54, 0x9c, 0x89, 0x8f, 0x4f,
	0x51, 0x59, 0x3c, 0x81, 0x71, 0x98, 0x36, 0x39, 0xda, 0x06, 0x9e, 0xc1, 0xe0, 0x59, 0x28, 0x2e,
	0x4c, 0x08, 0xb3, 0xc7, 0x33, 0x08, 0xe8, 0x10, 0xfe, 0xaf, 0xde, 0x4b, 0xfb, 0x9d, 0xfd, 0x44,
	0x40, 0xee, 0x82, 0x8a, 0x15, 0x4b, 0xbc, 0x82, 0x49, 0x21, 0x84, 0x29, 0xa4, 0xda, 0x3c, 0x98,
	0x72, 0x8d, 0x5d, 0x8f, 0x79, 0xb7, 0x45, 0x7b, 0x78, 0xf3, 0xc7, 0xb9, 0xb0, 0x9e, 0x9b, 0xb6,
	0xa2, 0x9d, 0x0f, 0xd8, 0xcf, 0x5e, 0x03, 0xa9, 0xd9, 0xdb, 0xed, 0x16, 0x0f, 0x77, 0x6e, 0xe8,
	0x32, 0xce, 0xa7, 0x1d, 0xc8, 0x9d, 0x8f, 0xf6, 0xde, 0x06, 0xfe, 0xff, 0x5e, 0xfe, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x1e, 0xb9, 0xb4, 0xf7, 0x01, 0x00, 0x00,
}
